[phases.setup]
nixPkgs = ['maven', 'openjdk17']

[phases.build]
cmds = ['mvn clean package -DskipTests']

[phases.deploy]
cmd = 'java -Dserver.port=$PORT $JAVA_OPTS -jar target/*.war'

[variables]
MAVEN_OPTS = '-Xmx1024m'
